[Export]
baked_state = false
baked_notebookfile = false
offer_binder = true
ignore_cache = [
    "index.jl",
]
slider_server_url="https://fuzzy.edge.silentech.gr"

create_index = false
exclude = [
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
]

[SliderServer]
port = 50001
host = "0.0.0.0"
exclude=[
    # these are in the repo but not used on the website
    "tools/*",
    "PlutoPages.jl",
    
    # notebooks not interactive

    # don't run homeworks
    "*/hw*.jl",
]
